# Generated by Django 2.2.12 on 2020-06-21 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(default='a@a.com', max_length=254)),
                ('objective', models.TextField()),
                ('skills', models.TextField()),
                ('interests', models.TextField()),
                ('awards', models.TextField()),
                ('involvement', models.TextField()),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('start_year', models.DateField(default='0000-00-00')),
                ('end_year', models.DateField(default='0000-00-00')),
                ('job_description', models.TextField()),
                ('program', models.CharField(max_length=200)),
                ('insitution', models.CharField(max_length=100)),
                ('start_year_ed', models.DateField(default='0000-00-00')),
                ('end_year_ed', models.DateField(default='0000-00-00')),
                ('education_description', models.TextField()),
                ('ref_name', models.CharField(max_length=100)),
                ('ref_position', models.CharField(max_length=100)),
                ('ref_company', models.CharField(max_length=100)),
                ('ref_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
