# Generated by Django 2.2.12 on 2020-06-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
