# Generated by Django 2.2.12 on 2020-06-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200621_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='end_year_ed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='start_year_ed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
