# Generated by Django 2.2.12 on 2020-06-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.CharField(default='defualt', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='interests',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='job_title',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='objective',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='phone_number',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
