# Generated by Django 2.2.12 on 2020-06-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200617_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=200)),
                ('insitution', models.CharField(max_length=100)),
                ('start_year_ed', models.DateField()),
                ('end_year_ed', models.DateField()),
                ('education_description', models.TextField()),
            ],
        ),
    ]
