# Generated by Django 2.2.12 on 2020-06-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200618_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='references',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_name', models.CharField(max_length=100)),
                ('ref_position', models.CharField(max_length=100)),
                ('ref_company', models.CharField(max_length=100)),
                ('ref_contact', models.CharField(max_length=100)),
            ],
        ),
    ]
